# Generated by Django 3.0.8 on 2020-08-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
