# Generated by Django 3.0.8 on 2020-08-04 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blick', '0005_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
